# Generated by Django 2.0 on 2019-09-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='doc_male.png', upload_to='app/img/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='patient_icon.png', upload_to='app/img/'),
        ),
    ]
