# Generated by Django 2.0 on 2019-09-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190921_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='doc_male.png', upload_to='img/'),
        ),
    ]
